files = ['SRR12007825', 'SRR12007837', 'SRR12007843', 'SRR12007847', 'SRR12007849', 'SRR12007851', 'SRR12007855', 'SRR12007861', 'SRR12007869']


rule all:
    input:
        'results/multiqc_report.html'


# Initial quality control
rule fastqc:
    input:
        fastq = 'data/{name}.fastq.gz'
    output:
        fastqc = 'results/{name}_fastqc.html'
    params:
        outdir = 'results/'
    conda:
        'envs/fastqc_env.yaml'
    shell:
        '''
        fastqc {input.fastq} -o {params.outdir}
        '''

# Aggregate the fastqc files
rule multiqc:
    input:
        expand('results/{name}_fastqc.html', name = files)
    output:
        report = 'results/multiqc_report.html'
    params:
        outdir = 'results/'
    conda:
        'envs/multiqc_env.yaml'
    shell:
        '''
        multiqc {params.outdir} -o {params.outdir}
        '''
